/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>, '//' | '//form/' | '//menu/' | '//modal/' | '//modal/form/' | '//table/' | '//utils/conf/' | '//utils/confirm/' | '//utils/file/' | '//utils/generator/' | '//utils/init/' | '//utils/request/' | '//utils/resolver/' | '//utils/type/'>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//form/': RouteRecordInfo<'//form/', '/form', Record<never, never>, Record<never, never>>,
    '//menu/': RouteRecordInfo<'//menu/', '/menu', Record<never, never>, Record<never, never>>,
    '//modal/': RouteRecordInfo<'//modal/', '/modal', Record<never, never>, Record<never, never>>,
    '//modal/form/': RouteRecordInfo<'//modal/form/', '/modal/form', Record<never, never>, Record<never, never>>,
    '//table/': RouteRecordInfo<'//table/', '/table', Record<never, never>, Record<never, never>>,
    '//utils/conf/': RouteRecordInfo<'//utils/conf/', '/utils/conf', Record<never, never>, Record<never, never>>,
    '//utils/confirm/': RouteRecordInfo<'//utils/confirm/', '/utils/confirm', Record<never, never>, Record<never, never>>,
    '//utils/file/': RouteRecordInfo<'//utils/file/', '/utils/file', Record<never, never>, Record<never, never>>,
    '//utils/generator/': RouteRecordInfo<'//utils/generator/', '/utils/generator', Record<never, never>, Record<never, never>>,
    '//utils/init/': RouteRecordInfo<'//utils/init/', '/utils/init', Record<never, never>, Record<never, never>>,
    '//utils/request/': RouteRecordInfo<'//utils/request/', '/utils/request', Record<never, never>, Record<never, never>>,
    '//utils/resolver/': RouteRecordInfo<'//utils/resolver/', '/utils/resolver', Record<never, never>, Record<never, never>>,
    '//utils/type/': RouteRecordInfo<'//utils/type/', '/utils/type', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes: '/' | '//' | '//form/' | '//menu/' | '//modal/' | '//modal/form/' | '//table/' | '//utils/conf/' | '//utils/confirm/' | '//utils/file/' | '//utils/generator/' | '//utils/init/' | '//utils/request/' | '//utils/resolver/' | '//utils/type/' | '//utils/conf' | '//utils/confirm' | '//utils/file' | '//form' | '//modal/form' | '//utils/generator' | '//utils/init' | '//menu' | '//modal' | '//utils/request' | '//utils/resolver' | '//table' | '//utils/type' | '//utils'
      views: 'default'
    }
    'src/views/index/index.vue': {
      routes: '//'
      views: never
    }
    'src/views/index/form/index.vue': {
      routes: '//form/'
      views: never
    }
    'src/views/index/menu/index.vue': {
      routes: '//menu/'
      views: never
    }
    'src/views/index/modal/index.vue': {
      routes: '//modal/'
      views: never
    }
    'src/views/index/modal/form/index.vue': {
      routes: '//modal/form/'
      views: never
    }
    'src/views/index/table/index.vue': {
      routes: '//table/'
      views: never
    }
    'src/views/index/utils/conf/index.vue': {
      routes: '//utils/conf/'
      views: never
    }
    'src/views/index/utils/confirm/index.vue': {
      routes: '//utils/confirm/'
      views: never
    }
    'src/views/index/utils/file/index.vue': {
      routes: '//utils/file/'
      views: never
    }
    'src/views/index/utils/generator/index.vue': {
      routes: '//utils/generator/'
      views: never
    }
    'src/views/index/utils/init/index.vue': {
      routes: '//utils/init/'
      views: never
    }
    'src/views/index/utils/request/index.vue': {
      routes: '//utils/request/'
      views: never
    }
    'src/views/index/utils/resolver/index.vue': {
      routes: '//utils/resolver/'
      views: never
    }
    'src/views/index/utils/type/index.vue': {
      routes: '//utils/type/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
